# Generated by Django 4.1.2 on 2022-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_redirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='url_short',
            field=models.CharField(default='j', max_length=100),
        ),
        migrations.AlterField(
            model_name='urls',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date last modified'),
        ),
    ]
