# Generated by Django 4.1.2 on 2022-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_redirect', '0002_urls_url_short_alter_urls_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
