# Generated by Django 4.2.4 on 2023-08-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_redirect', '0002_urls_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
