# Generated by Django 4.2.4 on 2023-08-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_redirect', '0003_rename_urls_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
